"""
Application configuration defaults.
"""

DEFAULT_SYMBOL_NR = "NR0"
DEFAULT_SYMBOL_CL_DISPLAY = "CL"
DEFAULT_INTERVAL_NR = 1.0
DEFAULT_INTERVAL_CL = 1.0
DEFAULT_TICK_SIZE_NR = 5.0
DEFAULT_LEVERAGE = 10.0
DEFAULT_TRADE_FEE = 6.15
DEFAULT_MAX_POINTS = 2000
DEFAULT_MAX_POINTS_STREAM = 100
DEFAULT_MAX_TICK_ROWS = 1000
